dubinc/dub

- components/home/demo.tsx
Fixes an error with some URLs being parsed incorrectly. See:
> fix: some URLs not being parsed on the homepage

- components/shared/modal.tsx
Thanks a lot @snazzah – your fix was correct! I missed the fact that the `desktop-modal` div was full screen so your way of using ref is the right way to go. Sorry for closing your PR prematurely! :sweat_smile:
> Adding back @Snazzah's changes

- components/app/modals/add-edit-link-modal.tsx
[This commit](https://github.com/steven-tey/dub/commit/f8b4bda4ad3d7f0cb0cbd48afd088e02273cb8df) forgot to account for numbers in links, noticed it while making other changes.
> fix: fix key regex pattern when managing links

- components/app/link-card.tsx
- components/app/modals/add-edit-link-modal.tsx
- components/app/settings/landing-page.tsx
- components/app/settings/plan-usage.tsx
- components/shared/tooltip.tsx
- lib/auth.ts
- lib/cron.ts
- lib/swr/use-project.ts
- lib/swr/use-usage.ts
- lib/types.ts
- package.json
- pages/api/projects/[slug]/usage.ts
- pages/api/stripe/webhook.ts
- pages/api/usage/index.ts
- pages/app/[slug]/[key].tsx
- prisma/schema.prisma
Users can now invite other users to their projects and the permission/usage quota will be shared with them.
This is made possible via:
- `usageLimit` is now propagated to the individual projects from their owners as `ownerUsageLimit`
- `ownerExceededUsage` field created to propagate owner usage state down to their projects
> Implemented initial RBAC features

- package.json
- pages/api/edge/metatags.ts
- yarn.lock
This PR makes the switch from `ultrahtml` to `node-html-parser` for parsing HTML, mainly because the former has some slight quirks in parsing weirdly-formatted attributes like `content` in meta tags. It also utilizes the library's `querySelector` API, and makes the codebase a tad bit more easy to read--and type safe--by reducing lines of code in the main logic. Using `node-html-parser` also removes the need to manually escape HTML entities that causes the JSON response to sometimes break.
> switch to node-html-parser for parsing

- pages/api/projects/[slug]/users.ts
Prevent removing the only user from a project so that it is just lost to the void.
Ideally, this would also need to be fixed in the UI, but this is a simple fix for now.
I have also written an email to support asking for the project back as it's just out there with no members.
> Prevent removing only user from project.

- app/ui/stats/index.tsx
- app/ui/stats/toggle.tsx
- components/stats/index.tsx
- components/stats/toggle.tsx
Fix `z` value on stats pages to prevent popovers displaying behind components.
Before:
After:
> Fix `z` value on stats pages

- lib/edge-config.ts
No need to initialize the Set (which will already iterate over the array).
The Set would be useful if you were planning to reuse it but not for one time use.
```js
var arr = Array.from({length: 100_000}).map((_, i) => `item${i}`);
var start = Date.now();
new Set(arr).has('notfound');
var end = Date.now();
console.log(`${end - start}ms`); // 13ms
```
```js
var arr = Array.from({length: 100_000}).map((_, i) => `item${i}`);
var start = Date.now();
arr.includes('notfound');
var end = Date.now();
console.log(`${end - start}ms`); // 1ms
```
> chore(refactor): use array.includes()

- pages/api/edge/metatags.ts
Thanks for the project!
I was wondering if you meant to allow cross-origin requests to the metadata api? I've enabled it in this PR if you're interested.
> Add CORS header to metatags api

- app/dub.co/tools/metatags/content.tsx
- pages/api/edge/metatags.ts
This PR is a follow up to #347 to also add CORS headers to the `OPTIONS` request that the browser sends before making the actual request.
This one I tested using my own vercel app and it's fully working, so there shouldn't need to be any further changes after this one.
Thanks!
> Follow up to Add CORS header to metatags api (OPTIONS request)

- README.md
the link for .env.example redirects to 404 page, changed to redirect to .env.example of the repo.
> fix: Updated Readme file

- apps/web/app/api/edge/metatags/route-wip.ts
- apps/web/app/api/edge/metatags/utils.ts
- apps/web/app/api/edge/stats/[endpoint]/route.ts
- apps/web/app/api/route.ts
- apps/web/app/rewrite/[url]/page.tsx
- apps/web/lib/tinybird.ts
- apps/web/lib/upstash.ts
- apps/web/package.json
- apps/web/pages/api/edge/metatags.ts
- apps/web/scripts/lua-convert.ts
- pnpm-lock.yaml
Switch edge API routes to App Router since https://github.com/vercel/next.js/issues/48295 is now fixed
> Switch to app router edge runtime

- apps/docs/api-reference/endpoint/bulk-create-links.mdx
- apps/web/app/api/callback/expire/route.ts
- apps/web/app/expired/[domain]/[key]/page.tsx
- apps/web/app/protected/[domain]/[key]/page.tsx
- apps/web/lib/api/links.ts
- apps/web/lib/middleware/link.ts
- apps/web/package.json
- apps/web/ui/links/link-card.tsx
- pnpm-lock.yaml
If you set an expiration date for your link, the user will see an "Expired Link" page when they try to access the link after the expiration date ([example](https://dub.sh/expire)).
> Add "Expired Link" page for expired links

- apps/web/app/protected/[domain]/[key]/page.tsx
Issue: #525
Removes `Dub.co` from being appended if the project is on a paid plan on the password protected page.
> Fix: Dub branding on password protected page

- apps/web/ui/projects/project-card.tsx
Fixed a small issue for the migration notice to show improperly on mobile devices.
| Before | After |
|-|-|
| ![](https://get.snaz.in/A3RUH82.png) | ![](https://get.snaz.in/3sZhTKj.png) |
> fix: fix migration notice on mobile

- apps/web/lib/edge-config.ts
There's an edge case for blacklist checks where it returns `true` if the list is empty. This means if there was an exception thrown or there were no results, it would return `true` and thus block the request. This can be seen in the local dev experience because there are no results by default. This PR should fix that.
> Add support for empty blacklist lists

- apps/docs/integrations/make.mdx
- apps/docs/integrations/pipedream.mdx
- apps/docs/integrations/raycast.mdx
- apps/docs/integrations/zapier.mdx
We recently introduced markdown in the description, but it appears that it wasn't error handled properly. As a result, `<>` is parsed as invalid MDX, which throws and error.
This PR fixes that error by replacing it with `x`. In the future, it will be fixed by fixing it so that when it errors, it just displays the string.
> Hotfix: Fix MDX parsing issue in integrations

- apps/docs/local-development.mdx
The [Local Development docs page](https://dub.co/docs/local-development#step-1-local-setup) currently instructs the user to run `cp .env.example .env`, but `.env.example` is in the `apps/web` directory, not the root.
This PR updates the command to `cp apps/web/.env.example apps/web/.env`. Alternatively, we could add an instruction to navigate into `apps/web` before running the `cp` command.
> Update .env copy command in Local Development doc

- apps/web/ui/links/link-card.tsx
Small change, helps differentiate links more similar to cloaked links.
> feat: add lock icon to protected link cards

- apps/docs/integrations.mdx
The docs currently log some warnings, like this one:
```
Warning: Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?
```
This PR fixes those props.
> Update SVG props to fix docs MDX warnings

- apps/web/ui/layout/user-dropdown.tsx
This PR fixes the stroke width of the logout icon in the user dropdown on the dashboard. It wasn't used from the Lucide icon library like the others.
> Fix: icon stroke width in user dropdown

- apps/web/ui/charts/areas.tsx
This should fix the ugly black area line animations happening when chart start and end dates change.
> Prevent ugly chart x-scale animations when start/end dates change

- apps/web/lib/openapi/index.ts
Before: `229.85 KB` 
After: `88.57 KB`
> OpenAPI spec: Add error responses as reusable component

- apps/web/ui/modals/add-edit-link-modal/index.tsx
Safari seems to have an issue with using `navigator.clipboard` to copy text without it being the direct result of a user action. In this case waiting for a request before copying the shortlink seems to be the issue.
We could probably investigate some other solutions, maybe even optimistically copying, but for now this seems to fix the UI hanging in Safari.
Closes #684
> Fix link creation UI hanging in Safari

- apps/web/ui/layout/user-survey/index.tsx
- packages/ui/src/popup.tsx
The popup animation was a little glitchy on some pages due to how we animating the transforms outside of the `position: fixed` element.
To keep the `Popup` component unopinionated, I moved the animations out of `Popup` and into `UserSurveyPopupInner`, rather than move the `fixed` positioning and other styles into `Popup`.
Tip: hide whitespace changes when viewing the diff!
> ENG-266: Fix user survey popup animation

- packages/ui/package.json
- packages/ui/src/link-preview.tsx
Current the metatags tool doesn't work if the target url have query (check screenshot below). This PR is about to fix it
Check out the live url https://dub.co/tools/metatags?url=https%3A%2F%2Fogcool.vercel.app%2Fpreview%3Fname%3DWave%26d%3DeyJtb2RpZmljYXRpb25zIjpbeyJuYW1lIjoiVGV4dCIsInRleHQiOiJTbyBmdWNraW5nIGdvb2QifV0sInRlbXBsYXRlSWQiOiJ0cGxfVG5sbFBnMENrUCJ9
> Escape `debouncedUrl` before send to api to support url with query

- apps/web/ui/modals/add-edit-link-modal/android-section.tsx
- apps/web/ui/modals/add-edit-link-modal/cloaking-section.tsx
- apps/web/ui/modals/add-edit-link-modal/expiration-section.tsx
- apps/web/ui/modals/add-edit-link-modal/geo-section.tsx
- apps/web/ui/modals/add-edit-link-modal/ios-section.tsx
- apps/web/ui/modals/add-edit-link-modal/og-section.tsx
- apps/web/ui/modals/add-edit-link-modal/password-section.tsx
- apps/web/ui/shared/pro-badge-tooltip.tsx
- packages/ui/src/tooltip.tsx
| Free Workspace | Pro Workspace |
| - | - |
| ![Screenshot 2024-04-27 at 11 09 21 PM](https://github.com/dubinc/dub/assets/2547408/0b53bad3-d2d4-46aa-900a-8e435ae8ed8b) | ![Screenshot 2024-04-27 at 11 09 31 PM](https://github.com/dubinc/dub/assets/2547408/04b82d37-712e-479c-9361-1f84a1e4374a) |
> ENG-292: Use `InfoTooltip` instead of "Pro" `BadgeTooltip` for upgraded workspaces

- apps/web/app/api/links/[linkId]/route.ts
- apps/web/app/api/links/bulk/route.ts
When sending invalid JSON to **PATCH**  `/links/{linkId}` and **POST** `/links/bulk`, we're getting an _"internal server error"_  instead of the more helpful _"bad request"_ error.
However, **POST** `/links` gets it right and tells us it's a "bad request" due to invalid JSON.
I believe this will help everyone using the API to have a smoother and more predictable experience.
I've already fixed it by first checking:
```ts
const bodyRaw = await parseRequestBody(req);
const links = bulkCreateLinksBodySchema.parse(bodyRaw);
```
I hope this helps make Dub better!
> Quick Fix: Inconsistent Error Responses for Invalid JSON in API Requests 

- packages/ui/src/filter/filter-select.tsx
Prevents the filter dropdown from getting a little larger while loading options, instead maintaining the size from the previous list state.
> Fix filter dropdown size changing when loading

- apps/docs/self-hosting.mdx
Removes extra text of `Terminal` in the code snippet example.
> Remove extra word from self-hosting.mdx

- apps/web/ui/links/link-card.tsx
#1023 
Ensuring that the popover is hidden immediately upon any modal-triggering keyboard shortcut, thus preventing it from overlaying the modal.
**Before Changes:**
https://www.loom.com/share/b6260197b30d4579bcb0b2c2042d23d1?sid=b8f72b40-830a-4fac-beee-694cfd459e22
**After Changes:**
https://www.loom.com/share/28e4a6e96741460095b812d166b57fa0?sid=1d955e65-92c7-4038-a026-555624a7d0ae
> fix: close popover when switching key in LinkCard component

- packages/ui/src/filter/filter-select.tsx
Right now, our `Filter.Select` component can potentially have a conflict if two items have the same label
This PR adds a "pseudo" suffix to the Command.Item value with the value that's passed in
The downside is you can also filter by those values, but since those are usually randomly-generated unique IDs it shouldn't be too bad
Before:
https://github.com/user-attachments/assets/d0638702-ee79-40d6-aed6-2bbacfe2d3fe
After:
https://github.com/user-attachments/assets/73eb8bc4-31f0-4d20-970e-e626ae882f62
> Fix filter select conflicts

- apps/web/ui/modals/add-edit-link-modal/index.tsx
Makes domain `<select>` font size match key `<input>`
> Fix link modal domain `<select>` font size

- packages/ui/src/button.tsx
In #1109, I added `grow` to the button's text wrapper, which means full-width buttons could end up with poorly aligned text. This ensures `text-left` is the default, still overridable by the `className` prop.
> Fix button text alignment

- packages/ui/src/hooks/use-media-query.ts
Previously, `useMediaQuery`'s `tablet` started at 641px, while Tailwind's `sm` started at 640px. Now both will start at 640px.
This caused issues such as [ENG-372](https://linear.app/dubinc/issue/ENG-372)
> Align `useMediaQuery` breakpoints with Tailwind

- apps/web/ui/analytics/events/events-table.tsx
- packages/ui/src/table/table.tsx
Adds missing titles to events table columns. We could do tooltips instead if we'd like, but we'd probably still want a hover delay so they're not too obnoxious.
> Add missing titles to events table columns

- packages/ui/src/hooks/use-input-focused.ts
Capturing `focus`/`blur` events was getting in the way of listeners in the page. We can use `focusin` and `focusout` instead, since these events bubble up to the window.
> Fix focus/blur capturing in `useInputFocused`

- packages/utils/src/constants/dub-domains.ts
> feat: add `photos.google.com` to the list of allowed `ggl.link`

- apps/web/app/api/oauth/token/exchange-code-for-token.ts
- apps/web/app/api/slack/callback/route.ts
- apps/web/app/api/stripe/connect/callback/route.ts
- apps/web/emails/integration-installed.tsx
- apps/web/lib/integrations/install.ts
- apps/web/ui/oauth-apps/add-edit-app-form.tsx
- packages/utils/src/constants/index.ts
- packages/utils/src/constants/integrations.ts
- packages/utils/src/constants/misc.ts
1. Send an email after the integration installation
2. Use `installIntegration` in the OAuth installation process
> Improve the integration installation

- apps/web/app/api/links/[linkId]/route.ts
for UTM tags, we should only pass them to `processLink` if they have changed
> Fix UTM implementation

- packages/utils/src/constants/dub-domains.ts
Resolve problem preventing the use of search.google.com links with ggl.link
> feat: add search.google.com to the list of allowed ggl.link

- apps/web/app/api/links/bulk/route.ts
- apps/web/lib/api/links/bulk-update-links.ts
- apps/web/lib/zod/schemas/links.ts
This PR adds support for passing `externalIds` in `PATCH /links/bulk`
> Support externalIds in bulk update endpoint

- packages/tinybird/pipes/v1_events.pipe
I was unable to ```tb push``` until i found that typo and changed it
> Fix Typo in v1_events.pipe

- apps/web/ui/domains/domain-card-title-column.tsx
[![Bug Video](https://github.com/user-attachments/assets/f90ea944-b3c1-4991-8ad7-06a98163b7d0)](https://github.com/user-attachments/assets/f90ea944-b3c1-4991-8ad7-06a98163b7d0)
This pull request addresses an issue in the `DomainCardTitleColumn` component where titles passed as props were incorrectly assumed to be domains. When non-domain titles were provided, the component attempted to render them as links to `http://<title>`, leading to incorrect behavior.
- **Updated `DomainCardTitleColumn` component:**
- **Rendering Logic:**
- Utilized the `isValidUrl` function to check if the `title` is a valid URL.
- If `title` is a valid URL, render it as a clickable link.
- If not, render `title` as plain text within a `<div>` element, maintaining consistent styling.
**Before Fix:**
- Non-domain …
> fix(ui): handle non-domain titles in DomainCardTitleColumn component

- apps/web/lib/actions/create-user-account.ts
- apps/web/lib/actions/send-otp.ts
> Optimize disposable email domain validation using `SISMEMBER` instead of `SMEMBERS`

- apps/web/ui/layout/help/help-section.tsx
There is an unnecessary horizontal scrollbar on the help popup due to the class `overflow-scroll` so this PR changes the class to `overflow-y-scroll`
> Changing overflow on help popup to hide horizontal scroll bar

- apps/web/lib/auth/options.ts
Fixes [#1429](https://github.com/dubinc/dub/issues/1429)
This PR aims to fix the issue which is raised under #1429. To summarise the issue here, when a user selected any OAuth provider to log in but then cancels on the permission page, it was not getting redirected to the default login page. This issue was instead causing the redirection to be handled via the nextauth's default redirection mechanism since it was not able to find our own signin route. More details on the issue can be found in the issue link added above.
Added a signIn route in the pages configuration of nextAuth options. 
https://github.com/user-attachments/assets/45723130-0298-4229-a16d-4e821d7143c3
https://github.com/nextauthjs/next-auth/discussions/3682
> fix: redirection to login page on cancelling of consent of oauth providers

- apps/web/lib/zod/schemas/tags.ts
- apps/web/lib/zod/schemas/utm.ts
Fixes: #1647
Make sure that creating a UTM template with only whitespace characters is prevented. You should see "UTM name is required" error toast.
> fix(api): reorder `trim()` method calls in Zod schema

- apps/web/ui/modals/archive-domain-modal.tsx
Fixes #1652. `toast.promise` expects a function for success/error messages that returns either a `ReactNode` or a `string` — it does not support `Promises`. Using async/await caused the UI bug described in the issue.
1. Head over your `Settings > Domains` page
2. Archive any domain you have and click the "Undo" button in a toast
3. You should see a human-readable success messsage
4. Same when undoing the unarchive action
> fix(ui): correct toast message on domain archive/unarchive undo action

- apps/web/app/api/analytics/export/route.ts
- apps/web/app/api/analytics/route.ts
- apps/web/app/api/dashboards/route.ts
- apps/web/app/api/events/export/route.ts
- apps/web/app/api/events/route.ts
- apps/web/app/api/links/[linkId]/dashboard/route.ts
- apps/web/app/api/links/[linkId]/route.ts
- apps/web/app/api/links/[linkId]/transfer/route.ts
- apps/web/app/api/links/info/route.ts
- apps/web/lib/actions/invite-partner.ts
- apps/web/lib/api/links/get-link-or-throw.ts
> Update `getLinkOrThrow` to accept `workspaceId` instead of `workspace` object.

- apps/web/app/partners.dub.co/(apply)/apply/[programSlug]/application/form.tsx
- packages/ui/src/button.tsx
Use `enabled:` instead to avoid overriding disabled colors.
> Alternative to adding `!`s to `Button`

- packages/ui/src/icons/nucleo/calendar-days.tsx
We should be using the Outline version instead of Outline Duo
| Before | After |
|--------|--------|
| ![Screenshot 2024-12-20 at 2 26 52 PM](https://github.com/user-attachments/assets/8a33f3e9-e29c-4db8-90c0-57f12b76c83a) | ![Screenshot 2024-12-20 at 2 26 38 PM](https://github.com/user-attachments/assets/a3d9f17c-91b4-456c-84cf-ffa882fd7aa8) |
> Fix `CalendarDays` icon

- apps/web/ui/shared/search-box.tsx
Add Escape key functionality to blur the search input, fixing issue #1780.
> Unable to exit the search bar using the ESC key

- apps/web/.env.example
- apps/web/app/api/cron/shopify/order-paid/route.ts
- apps/web/app/api/shopify/integration/webhook/app-uninstalled.ts
- apps/web/app/api/shopify/integration/webhook/customers-data-request.ts
- apps/web/app/api/shopify/integration/webhook/customers-redact.ts
- apps/web/app/api/shopify/integration/webhook/order-paid.ts
- apps/web/app/api/shopify/integration/webhook/route.ts
- apps/web/app/api/shopify/integration/webhook/shop-redact.ts
- apps/web/app/api/shopify/pixel/route.ts
- apps/web/lib/integrations/shopify/process-order.ts
This pull request includes several changes to improve the handling of Shopify webhook events and the integration with Shopify. The most important changes include adding return messages for various webhook handlers, modifying the `orderPaid` function to handle different cases of `clickId`, and renaming and updating the Shopify pixel route.
* Added return messages for various webhook handlers to provide a response after processing. (`apps/web/app/api/shopify/integration/webhook/app-uninstalled.ts`, `apps/web/app/api/shopify/integration/webhook/customers-data-request.ts`, `apps/web/app/api/shopify/integration/webhook/customers-redact.ts`, `apps/web/app/api/shopify/integration/webhook/shop-redact.ts`) [[1]](diffhunk://#diff-f82c3036eb31aa885e6082b6a92e056fa4a6f819f055ff50a65569ed76cb1c50R16-R1 …
> Shopify: Improve efficiency of the webhook processing

- apps/web/app/app.dub.co/(auth)/invites/[code]/page.tsx
This PR fixes a small typo in the export name of the InitesPage component, changing it to InvitesPage for better clarity and consistency.
The typo doesn't seem to cause any functional issues, but i think correcting it helps with readability and avoids potential confusion for future contributors.
Let me know if you'd like me to adjust anything!
> Fix typo in page export: InitesPage -> InvitesPage

- apps/web/ui/webhooks/webhook-card.tsx
- apps/web/ui/webhooks/webhook-header.tsx
This pull request includes changes to improve the layout and readability of webhook components in the user interface. The most important changes involve adding CSS classes to handle text overflow and prevent layout shifts.
Improvements to layout and readability:
* [`apps/web/ui/webhooks/webhook-card.tsx`](diffhunk://#diff-a939a1aed9f0d9b8eca647e5f518815069cb60e074e90cfb2779b9ee2332f6adL16-R24): Added `flex-shrink-0` class to prevent the avatar from shrinking and `overflow-hidden` class to handle text overflow. Modified the URL display to use the `truncate` class for better text handling.
* [`apps/web/ui/webhooks/webhook-header.tsx`](diffhunk://#diff-cf9ebdcadb049a8bd873636ed234d8747e4f7ac03c4fd986f3507e8560868dc2L120-R120): Added `break-all` class to the URL link to ensure long URLs break …
> Make sure the webhook URL doesn't overflow the container

- apps/web/app/api/cron/domains/configure-dns/route.ts
- apps/web/app/api/cron/domains/delete/route.ts
- apps/web/app/api/cron/domains/transfer/route.ts
- apps/web/app/api/cron/domains/update/route.ts
- apps/web/app/api/cron/import/bitly/route.ts
- apps/web/app/api/cron/import/csv/route.ts
- apps/web/app/api/cron/import/rebrandly/route.ts
- apps/web/app/api/cron/import/short/route.ts
- apps/web/app/api/cron/links/delete/route.ts
- apps/web/app/api/cron/shopify/order-paid/route.ts
- apps/web/app/api/cron/usage/route.ts
- apps/web/app/api/cron/workspaces/delete/route.ts
- apps/web/app/api/webhooks/callback/route.ts
- apps/web/lib/cron/verify-qstash.ts
- Updated multiple API routes to read the raw body from requests instead of parsing JSON directly.
- Modified the `verifyQstashSignature` function to accept the raw body for signature verification.
- Ensured consistent handling of request bodies across various endpoints, improving reliability in signature validation.
> Refactor QStash signature verification to use raw request body

- packages/ui/src/tooltip.tsx
Adds `pointer-events-auto` to make sure tooltips are interactable when dialogs are opened and `body` receives a `pointer-events: none`
> Fix tooltips within dialogs

- apps/web/lib/webhook/utils.ts
This pull request includes changes to the `apps/web/lib/webhook/utils.ts` file to improve the identification of webhook receivers and simplify the code. The most important changes include adding a new entry to the `webhookReceivers` object and refactoring the `identifyWebhookReceiver` function to use destructuring for better readability.
Improvements to webhook receiver identification:
* [`apps/web/lib/webhook/utils.ts`](diffhunk://#diff-cb0a4cc386a034a28c0cd9286f9aea6327abb4ffca80c49cd704b2a9c70076b6R5): Added a new entry `"zapier.com": "zapier"` to the `webhookReceivers` object to ensure proper identification of Zapier webhooks.
Code simplification:
* [`apps/web/lib/webhook/utils.ts`](diffhunk://#diff-cb0a4cc386a034a28c0cd9286f9aea6327abb4ffca80c49cd704b2a9c70076b6L25-R28): Refactored …
> Update webhook receiver identification for Zapier

- apps/web/lib/api/links/process-link.ts
- apps/web/ui/links/short-link-input.tsx
Improve `allowedHostnames` implementation by updating the logic to check both the apex domain and the domain without the "www" prefix.
> Fix `allowedHostnames` implementation

- apps/web/app/api/webhooks/[webhookId]/route.ts
- apps/web/emails/webhook-failed.tsx
- apps/web/lib/actions/enable-disable-webhook.ts
- apps/web/lib/webhook/constants.ts
- apps/web/lib/webhook/failure.ts
- Introduced a new email template for notifying users when a webhook is failing to deliver.
- Updated the webhook failure threshold constants to support multiple notification thresholds.
- Modified the logic for handling webhook failures to send notifications based on the new thresholds.
- Added a new function to notify users when a webhook is disabled due to consecutive failures.
- Updated existing email templates to reflect the new failure threshold terminology.
> Refactor webhook failure handling and notifications

- apps/web/app/api/webhooks/[webhookId]/route.ts
- apps/web/emails/webhook-failed.tsx
- apps/web/lib/webhook/failure.ts
- apps/web/tests/tags/list-tags.test.ts
This pull request introduces changes to track and handle consecutive webhook failures. The most important changes include adding a new `consecutiveFailures` field to various parts of the codebase and updating the email notification content to reflect this new field.
Tracking consecutive failures:
* `apps/web/app/api/webhooks/[webhookId]/route.ts`: Added `consecutiveFailures` field to the webhook object. ([apps/web/app/api/webhooks/[webhookId]/route.tsR141](diffhunk://#diff-32500fa9d9575c404d91dd97dc6cb017f9ea98f0724e628551d28a5b5912ae55R141))
* [`apps/web/lib/webhook/failure.ts`](diffhunk://#diff-b16b78cb32159950effadeea3841e558ec846b773a07ab63acde98c84f7b2b76L83-R83): Updated the `notifyWebhookFailure` function to include the `consecutiveFailures` field when notifying workspace owners. …
> Update webhook failure notification template

- apps/web/app/api/cron/process-payouts/route.ts
Fix the error
```
Ensure you return a `Response` or a `NextResponse` in all branches of your handler.
```
> Adding a response message for cases with no pending sales

- apps/web/ui/links/link-title-column.tsx
> Fix link underline on Firefox

- apps/web/lib/analytics/constants.ts
- apps/web/lib/analytics/utils/get-start-end-dates.ts
- apps/web/ui/analytics/analytics-area-chart.tsx
- apps/web/ui/analytics/analytics-provider.tsx
- apps/web/ui/analytics/events/events-tabs.tsx
- apps/web/ui/analytics/toggle.tsx
- packages/ui/src/date-picker/calendar.tsx
- packages/ui/src/date-picker/date-range-picker.tsx
- packages/ui/src/date-picker/presets.tsx
A few other changes:
- Keyboard shortcut for "Last 30 days" and "Last 3 months" have been changed to `t` and `3` respectively
- Default Analytics date range is now `30d` instead of `24h` (on the API side the default is still `24h` though)
>  Add `mtd` and `qtd` presets

- packages/ui/src/input-select.tsx
Currently on mobile the default workspace selector and move link to folder selector are completely broken and dismiss instantly when attempting to choose an item.
This fixes that by disabling `useDismiss` from `@floating-ui/react` since it seems to be intercepting pointerdown and breaking things when it's not properly in use.
> Fix `<InputSelect adjustForMobile />` on mobile

- apps/web/ui/links/links-toolbar.tsx
Users/workspaces without folder access (e.g. free/pro users) couldn't perform bulk actions because `folders` is `undefined`. This adds special handling for when no selected links are in folders to avoid the `folders` check.
> Fix bulk actions for users w/o access to folders

- apps/web/ui/analytics/bar-list.tsx
- apps/web/ui/analytics/main.tsx
- Ensured the short link doesn't overlap with the analytics data values on the right
- When the percentage is shown on hover, the short link overflow size changes to ensure there is no overlap
- Fixed an issue found in which the color bars were not filling the entire row based on their actual percentage and would stop at the values, so when hovering it would make the bar smaller. Confusing when the value was 100%. Now fills the container based on actual percentage.
> Percentage responsive update and fixes

- apps/web/ui/modals/add-edit-tag-modal.tsx
- apps/web/ui/modals/add-edit-utm-template.modal.tsx
- apps/web/ui/modals/add-folder-modal.tsx
* Fixes the "Create folder" keyboard shortcut by using `useKeyboardShortcut`
* Adds keyboard shortcut for "Create tag" and "Create template"
> Fix + add Library create keyboard shortcuts

- packages/ui/src/hooks/use-keyboard-shortcut.tsx
- packages/ui/src/sheet.tsx
Prevents `useKeyboardShortcut` from triggering while a sheet is open unless `sheet=true`
> Fix keyboard shortcuts / sheets interactions

- apps/web/ui/modals/partner-link-modal.tsx
- packages/utils/src/functions/index.ts
- packages/utils/src/functions/regex-escape.ts
Partner links pointing to a destination URL w/o any path (e.g. `dub.co`) are currently parsed incorrectly because the `replace` is expecting a slash after the domain
> Fix partner link URL parsing

- apps/web/app/app.dub.co/(dashboard)/[slug]/settings/library/tags/tag-card.tsx
- apps/web/lib/middleware/app.ts
- apps/web/lib/middleware/utils/app-redirect.ts
- apps/web/ui/folders/folder-dropdown.tsx
- apps/web/ui/links/link-card.tsx
- apps/web/ui/links/link-title-column.tsx
* Updates middleware redirect from `/[slug]` to `/[slug]/links` to persist search params
* Updates `/[slug]` to `/[slug]/links` in several places so they don't need to pass through the redirect anyways
> Fix folder switching

- apps/web/lib/tinybird/record-click.ts
Addresses issue #2309 (and #1860) by ensuring only user-initiated requests are counted, preventing inflation from HEAD requests.
> Fix click tracking bug by filtering HEAD requests

- packages/utils/src/constants/plan-compare.tsx
This pull request updates two outdated URL references in the `plan-compare.tsx` file to ensure users are directed to the most accurate and current pages for documentation and support.
---
- ✅ Updated URL in the **Links** section:  
From: `https://dub.co/home`  
To: `https://dub.co/links`
- ✅ Updated URL in the **Support** section:  
From: `https://dub.co/help`  
To: `https://dub.co/contact/support`
- ✅ Removed obsolete `TODO` comments related to the above links
---
- Ensure all URLs point to the correct and most relevant destinations
- Improve user experience and navigation
- Clean up unnecessary inline comments for better code maintainability
---
- 🔧 **Chore:** Maintenance update to project URLs
---
---
- Resolves outdated URL references in the project's **plan comparison constants**
> chore: Update outdated URL references in plan-compare.tsx
