.env.example, README.md, pages/index.tsx
- Added required env vars and setup instructions to .env.example
- Added required env vars to Vercel deploy button
=> Improved self-hosted instructions

package.json
It is not a private project so I change the private to false
=> change to public

components/home/globe.tsx, lib/hooks/use-intersection-observer.ts
- Added fallback video for devices that don't support WebGL
- Use intersection observer to hide/show globe animation based on viewpoint
=> Optimized WebGL Globe

components/app/settings/delete-project.tsx, components/app/settings/landing-page.tsx, components/app/settings/plan-usage.tsx, lib/auth.ts, lib/middleware/root.ts, pages/api/projects/[slug]/domains/[domain]/root/clicks.ts, pages/api/projects/[slug]/domains/[domain]/root/index.ts, pages/app/[slug]/settings.tsx
Will probably make this a Pro feature eventually but for early adopters it'll be free forever 🤗
=> Added root redirect functionality

components/app/settings/plan-usage.tsx, components/home/pricing.tsx, components/shared/slider.tsx, components/shared/tooltip.tsx, package.json, yarn.lock
(still need to fix up Stripe integration though)
=> Shipped new pricing changes on landing page

components/app/link-card.tsx, components/app/modals/add-edit-link-modal.tsx, components/app/modals/add-project-modal.tsx, components/app/modals/delete-link-modal.tsx, components/app/modals/delete-project-modal.tsx, components/app/modals/edit-domain-modal.tsx, components/app/modals/stats-modal.tsx, components/home/link-card.tsx, components/layout/app/index.tsx, components/layout/app/list-box.tsx, components/shared/badge-select.tsx, components/shared/modal.tsx, components/shared/tooltip.tsx, components/stats/bar-chart/index.tsx, components/stats/clicks.tsx, components/stats/devices.tsx, components/stats/index.tsx, components/stats/locations.tsx, components/stats/toggle.tsx, lib/constants.ts, pages/index.tsx
- Modified `<Modal/>` to act as modal sheets on mobile
- Modified `<Tooltip/>` to act as modal sheets on mobile
- Fixed header padding issue
=> Optimized Mobile Design

components/app/link-card.tsx, components/app/modals/add-edit-link-modal.tsx, components/app/modals/delete-link-modal.tsx, components/app/modals/link-qr-modal.tsx, components/home/link-card.tsx, lib/constants.ts, lib/utils.ts
Also added `getApexDomain` function that gets the apex domain of a given domain, accounting for cases where the domain could be either a subdomain (e.g. `dub.vercel.app`) or a second level domain (e.g. `.co.uk`)
=> Converted urlHostname to apexDomain

package.json, pages/api/edge/metatags.ts
hey @steven-tey! this pr might require some changes, as you were previously recording all the tags from the `recordMetatags` function in `@/lib/upstash`. LMK if it does need any!
=> feat: add new implementation to fetch meta tags

app/(marketing)/atom/route.ts
Saw your [tweet](https://twitter.com/steventey/status/1652706421610536960) and it caught my eye that you have extra commas between entries in your XML. 
This quick pull request will remove them and make the XML valid.
=> Fix changelog rss feed xml formatting

app/(marketing)/changelog/[slug]/page.tsx, app/(marketing)/components/mdx.tsx, components/app/links/link-card-placeholder.tsx, components/app/links/link-card.tsx, components/app/links/link-filters.tsx, components/app/modals/add-edit-link-modal/index.tsx, components/shared/copy-button.tsx, components/shared/modal.tsx, lib/constants/index.ts, middleware.ts, package.json, posts/changelog/duplicating-links.mdx, posts/changelog/keyboard-shortcuts.mdx, prisma/schema.prisma, tsconfig.json, yarn.lock
Inspired by @fmerian https://github.com/steven-tey/dub/issues/164
https://user-images.githubusercontent.com/28986134/235563587-aaacd9e1-645f-45d1-a072-89def55aa62d.mp4
=> Added keyboard shortcuts

lib/middleware/link.ts, lib/middleware/utils.ts, middleware.ts, posts/changelog/pass-url-parameters.mdx
=> Support passthrough query params (utm, ref, etc.)

components/app/modals/add-project-modal.tsx, lib/utils.ts, package.json, yarn.lock
Use https://github.com/sindresorhus/slugify to handle slugification of names.
Before:
After:
=> Improve slugification of names

app/admin/components/ban.tsx, app/admin/components/impersonate-project.tsx, app/admin/components/impersonate-user.tsx, app/dub.sh/metatags/page.tsx, app/ui/home/stats.tsx, app/ui/home/testimonials.tsx, app/ui/modals/add-edit-link-modal/index.tsx, app/ui/modals/add-edit-link-modal/rewrite-section.tsx, app/ui/switch.tsx, app/ui/tooltip.tsx, components/app/modals/add-edit-domain-modal.tsx, components/app/modals/add-edit-link-modal/index.tsx, components/app/modals/add-edit-link-modal/rewrite-section.tsx, content/changelog/link-cloaking.mdx, content/help/how-to-create-link.mdx, content/help/how-to-redirect-root-domain.mdx, lib/api/links.ts, lib/constants/index.ts, lib/middleware/link.ts, lib/types.ts, package.json, pages/api/links/[key]/index.ts, pages/api/links/index.ts, pages/api/projects/[slug]/domains/[domain]/index.ts, prisma/schema.prisma, yarn.lock
=> Add link cloaking feature

app/api/unsplash/download/route.ts, app/api/unsplash/search/route.ts, app/api/unsplash/utils.ts, app/ui/modals/add-edit-link-modal/og-section.tsx, app/ui/popover.tsx, components/app/modals/add-edit-link-modal/og-section.tsx, components/app/modals/add-edit-link-modal/unsplash-search.tsx, components/shared/icons/unsplash.tsx, content/changelog/custom-social-cards.mdx, package.json, yarn.lock
Sneak peek 👀 
https://github.com/steven-tey/dub/assets/28986134/9d79c133-9e0e-4da5-8432-e2443bb3ed01
=> Unsplash Integration

app/dub.co/(blog-post)/blog/[slug]/page.tsx, app/dub.co/customers/[slug]/page.tsx, app/ui/home/testimonials.tsx, content/customers/prisma.mdx
Added context to headlines for quick, easy read/scan of the customer story
=> Update customer story

lib/constants/content.tsx
this PR polishes the details.
Currently, there are some inconsistencies in the headlines (uppercase vs. lowercase, see screenshot), and this PR just fixes them.
=> fix: Edit headlines for consistency

apps/web/app/protected/[domain]/[key]/action.ts, apps/web/app/protected/[domain]/[key]/form.tsx, apps/web/app/protected/[domain]/[key]/loading.tsx, apps/web/app/protected/[domain]/[key]/page.tsx, apps/web/app/ui/modals/add-edit-link-modal/index.tsx, apps/web/components/app/modals/add-edit-link-modal/index.tsx, apps/web/lib/middleware/link.ts, apps/web/lib/planetscale.ts
=> Improve password-protected links

apps/web/ui/links/links-container.tsx
=> fix pagination rendering 0

README.md
I have improved the documantation by fixing a few spelling mistakes in README.md file
=> Fix: documantation spelling mistake

apps/docs/self-hosting/guide.mdx
missed an i - not much but im a little bit of a perfectionist
=> tinybird typo

apps/web/app/api/cron/import/bitly/route.ts, apps/web/app/api/cron/import/csv/route.ts, apps/web/app/api/cron/import/rebrandly/route.ts, apps/web/app/api/cron/import/short/route.ts, apps/web/vercel.json
=> Fix max duration for Vercel Free plan

apps/web/ui/layout/project-select.tsx, apps/web/ui/projects/project-card.tsx
This PR fixes #568 
cc @steven-tey
=> ui-fix: long project's name ui aberration fixed

apps/web/app/api/links/[linkId]/route.ts, apps/web/app/api/links/info/route.ts, apps/web/app/api/route.ts, apps/web/lib/api/links.ts
=> Polyfill `shortLink` in API responses

apps/web/ui/account/upload-avatar.tsx, apps/web/ui/layout/settings-layout.tsx, apps/web/ui/projects/upload-logo.tsx, packages/ui/src/form.tsx
=> Patched Narrow UI Tabs Bug at /settings

apps/web/app/api/me/route.ts, apps/web/app/api/qr/route.tsx, apps/web/app/api/route.ts, apps/web/lib/api/links.ts, apps/web/lib/qr/constants.ts, apps/web/lib/qr/index.tsx, apps/web/lib/qr/types.ts, apps/web/lib/qr/utils.tsx, apps/web/ui/modals/link-qr-modal.tsx, pnpm-lock.yaml
=> Add QR Code API

apps/web/app/api/projects/[slug]/invites/accept/route.ts, apps/web/app/api/projects/[slug]/invites/reset/route.ts, apps/web/app/api/projects/[slug]/invites/route.tsx, apps/web/app/api/projects/route.ts, apps/web/app/app.dub.co/(auth)/invites/[code]/page.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/settings/people/page-client.tsx, apps/web/lib/api/users.ts, apps/web/lib/auth/index.ts, apps/web/lib/middleware/app.ts, apps/web/lib/types.ts, apps/web/package.json, apps/web/prisma/schema.prisma, apps/web/scripts/seed-invite-codes.ts, apps/web/ui/modals/invite-code-modal.tsx, packages/ui/src/button.tsx, packages/utils/src/constants/misc.ts, pnpm-lock.yaml
=> Add invite link feature

apps/web/app/app.dub.co/(auth)/login/form.tsx, apps/web/app/app.dub.co/(auth)/register/form.tsx
After clicking google or github login button in login and register page it redirects to auth page but when we click back  button is still in loading state and other buttons in disabled state. I fixed this issue.
=> google and github login button loading fixed

apps/web/app/api/cron/links/delete/route.ts, apps/web/app/api/cron/links/event/route.ts, apps/web/app/api/links/[linkId]/route.ts, apps/web/app/api/links/bulk/route.ts, apps/web/app/api/links/sync/route.ts, apps/web/app/api/tags/[id]/route.ts, apps/web/lib/analytics.ts, apps/web/lib/api/domains.ts, apps/web/lib/api/links.ts, apps/web/lib/tinybird.ts, apps/web/lib/zod/schemas/analytics.ts, apps/web/scripts/bulk-delete-links.ts, apps/web/scripts/sync-tag-analytics.ts, apps/web/ui/analytics/clicks.tsx, apps/web/ui/analytics/index.tsx, apps/web/ui/analytics/share-popover.tsx, apps/web/ui/analytics/tag-selector.tsx, apps/web/ui/analytics/toggle.tsx
=> Add tag-based analytics

packages/ui/src/input-select.tsx
https://github.com/dubinc/dub/assets/92092993/e6a18cf4-0aeb-4515-93ce-46c3cd12bbec
=> feat: improve usability on input-select

apps/web/ui/analytics/domain-selector.tsx, apps/web/ui/analytics/tag-selector.tsx, apps/web/ui/modals/add-edit-domain-modal/index.tsx, apps/web/ui/modals/add-edit-tag-modal.tsx, apps/web/ui/modals/provider.tsx, packages/ui/src/input-select.tsx
This PR introduces an empty state for properly routing the user to the correct modal for creating filter options.
https://github.com/dubinc/dub/assets/92092993/1d55cd28-f108-494b-8347-88b39a77354b
=> Introduce Empty Filter State

packages/ui/src/input-select.tsx
Fixes the glitches with the mobile input-select component.
=> Mobile Input + Drawer Glitch fix

apps/web/app/api/links/info/route.ts, apps/web/lib/api/links/bulk-create-links.ts, apps/web/lib/api/links/create-link.ts, apps/web/lib/api/links/edit-link.ts, apps/web/lib/api/links/get-links-for-workspace.ts, apps/web/lib/api/links/utils.ts
- Add missing attributes (`workspaceId`, `tags`, `qrCode`, etc) to the link info response.
- Move the link response transformation logic to the utils.
=> Update link info api response

apps/web/app/api/route.ts
=> Revert "set security requirement to optional for all paths"

apps/web/app/api/workspaces/route.ts, apps/web/lib/zod/schemas/links.ts
- add `ws_` prefix to the `id` returned by create workspace api
- update `updateLinkBodySchema` to make it optional
=> Api changes

apps/web/app/api/links/[linkId]/route.ts, apps/web/app/api/links/route.ts
handle duplicate externalId error from Prisma
=> Handle Duplicate ExternalId error

apps/web/lib/jackson.ts, apps/web/package.json, pnpm-lock.yaml
=> Upgrade `@boxyhq/saml-jackson` 

apps/web/ui/account/upload-avatar.tsx, apps/web/ui/layout/help/contact-form.tsx, apps/web/ui/modals/add-edit-link-modal/og-section.tsx, apps/web/ui/modals/add-edit-link-modal/preview.tsx, apps/web/ui/modals/add-edit-link-modal/unsplash-search.tsx, apps/web/ui/workspaces/upload-logo.tsx, packages/ui/src/image-upload.tsx, packages/ui/src/index.tsx, packages/ui/src/modal.tsx
Implements the new `ImageUpload` component for avatar, workspace logo, and contact form.
=> Implement `ImageUpload` across the app

apps/web/lib/analytics/clicks.ts, apps/web/lib/analytics/constants.ts, apps/web/ui/analytics/date-range-picker.tsx, apps/web/ui/domains/domain-card.tsx, apps/web/ui/links/link-card.tsx
=> Fix all-time clicks count bug (#901)

.gitignore, apps/web/app/mailto/[url]/page.tsx, apps/web/lib/middleware/link.ts
=> Add support for mailto: links

apps/web/lib/middleware/create-link.ts
Fixes https://x.com/alexhbass/status/1792221199826571733
=> Make sure the new link shortcut takes the full URL

apps/web/ui/analytics/share-popover.tsx, apps/web/ui/analytics/toggle.tsx, packages/ui/src/filter/filter-list.tsx, packages/ui/src/filter/filter-select.tsx
=> Move "Clear filters" button

packages/ui/src/animated-size-container.tsx, packages/ui/src/filter/filter-select.tsx
https://github.com/dubinc/dub/assets/2547408/c1b7b2c6-8e7e-4c37-a951-37e889226656
=> Add fade to bottom of filter scroll container

packages/ui/src/filter/filter-select.tsx
Fixes some issues with changing opening/closing the popup by using a separate component
=> Filter fade improvements

apps/web/app/app.dub.co/(dashboard)/workspaces/page.tsx, apps/web/lib/api/workspaces.ts, apps/web/lib/middleware/app.ts, apps/web/lib/middleware/new-link.ts, apps/web/ui/layout/workspace-switcher.tsx, apps/web/ui/modals/delete-workspace-modal.tsx
https://github.com/dubinc/dub/assets/28986134/df6364c2-7038-4533-9db2-f9b42c86ddf9
=> Redirect to default workspace

apps/web/ui/analytics/analytics-card.tsx, apps/web/ui/analytics/toggle.tsx, apps/web/ui/analytics/top-links.tsx, apps/web/ui/analytics/utils.ts, packages/ui/src/filter/filter-select.tsx, packages/ui/src/tab-select.tsx
https://github.com/dubinc/dub/assets/2547408/2ae135d9-9eaa-4481-a312-fb6d8e6d0f1b
=> Defer fetching filter options until they're selected

apps/web/app/[domain]/placeholder.tsx, apps/web/app/api/stripe/webhook/route.ts, apps/web/ui/account/update-default-workspace.tsx, apps/web/ui/links/link-card.tsx, apps/web/ui/modals/transfer-domain-modal.tsx, apps/web/ui/welcome/intro.tsx, apps/web/ui/workspaces/upload-logo.tsx
**Fix Typo**
1.  workarouond -> workaround
2. webook -> webhook
3. Succesfully -> Successfully
4. `handlClickOnLinkCard` -> `handleClickOnLinkCard`
5. `setselectedWorkspace` -> `setSelectedWorkspace`
**Fix tailwind class**
`nderline-offset-4 -> underline-offset-4`
=> Fix typos and invalid tailwind class

apps/web/app/admin.dub.co/analytics/page.tsx, apps/web/app/api/analytics/events/route.ts, apps/web/app/app.dub.co/(dashboard)/demo/page.tsx, apps/web/lib/auth/workspace.ts, apps/web/ui/analytics/analytics-provider.tsx, apps/web/ui/analytics/events/events-link-type.tsx, apps/web/ui/analytics/events/events-table-menu.tsx, apps/web/ui/analytics/events/events-table.tsx, apps/web/ui/analytics/events/events-tabs.tsx, apps/web/ui/analytics/events/index.tsx, apps/web/ui/analytics/index.tsx, apps/web/ui/analytics/main.tsx, apps/web/ui/analytics/toggle.tsx, apps/web/ui/layout/nav-tabs.tsx
=> Add root domain / short link filtering

apps/web/lib/middleware/utils/is-supported-deeplink-protocol.ts
```
[
"mailto:",
"tel:",
"sms:",
"whatsapp:",
"tg:",
];
```
=> Support more deep link protocols

apps/docs/api-reference/endpoint/add-a-domain.mdx, apps/docs/api-reference/endpoint/create-a-domain.mdx, apps/docs/mint.json, apps/docs/sdks/typescript/domains/create.mdx, apps/web/app/api/domains/route.ts, apps/web/lib/openapi/domains/create-domain.ts, apps/web/lib/openapi/domains/index.ts, apps/web/lib/zod/schemas/domains.ts, apps/web/openapi.json
All our other resources use the term `create` so we're standardizing this for `domains` too.
=> Rename domains.add → domains.create

apps/web/app/admin.dub.co/revenue/page.tsx
=> Fix admin data issue

apps/web/lib/api/errors.ts
Regenerate the [dub-ts](https://github.com/dubinc/dub-ts) after merging this.
=> refactor: add x-speakeasy-error-message flag to error message schema

apps/web/lib/middleware/link.ts
=> Add `getFinalUrl` for deep links & link cloaking

apps/web/lib/api/links/process-link.ts, apps/web/tests/links/bulk-update-link.test.ts, apps/web/ui/modals/add-edit-link-modal/index.tsx
=> Improve invalid hostname error message

apps/web/app/layout.tsx, apps/web/lib/auth/session.ts, apps/web/lib/auth/workspace-edge.ts, apps/web/lib/auth/workspace.ts, apps/web/lib/middleware/axiom.ts, apps/web/lib/middleware/index.ts, apps/web/middleware.ts, apps/web/next.config.js, apps/web/package.json, pnpm-lock.yaml
Context: https://axiom.co/blog/changes-to-vercel-log-drains
Docs: https://github.com/axiomhq/next-axiom
Guide: https://axiom.co/docs/apps/vercel#migrate-from-vercel-app-to-next-axiom
=> Migrate to `next-axiom`

apps/web/lib/qr/index.tsx, apps/web/ui/modals/link-qr-modal.tsx
=> Fix QR Code missing Logo when downloaded as SVG

apps/web/app/api/oauth/apps/route.ts, apps/web/app/app.dub.co/(dashboard)/[slug]/integrations/[integrationSlug]/page-client.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/integrations/[integrationSlug]/page.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/integrations/manage/[integrationId]/page-client.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/integrations/page-client.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/integrations/page.tsx, apps/web/lib/actions/generate-client-secret.ts, apps/web/lib/types.ts, apps/web/lib/zod/schemas/oauth.ts, apps/web/prisma/schema/oauth.prisma, apps/web/ui/integrations/add-edit-integration-form.tsx, apps/web/ui/integrations/integration-card.tsx, apps/web/ui/integrations/oauth-app-credentials.tsx, apps/web/ui/modals/uninstall-integration-modal.tsx
- Fix the callback URLs UI (add and remove URLs dynamically)
- Store and display the partial client's secret
- Cleanup the types
=> Dub integrations follow up tasks

packages/ui/package.json, packages/ui/src/filter/filter-select.tsx, packages/ui/src/hooks/use-scroll-progress.ts, packages/ui/src/input-select.tsx, pnpm-lock.yaml
Adds collision awareness (decreases height to a certain point, then flips)
Shows all values initially
=> ENG-475: `InputSelect` improvements

apps/web/ui/links/link-details-column.tsx, apps/web/ui/links/link-title-column.tsx
I'm thinking this *might* help with some of the blank card virtualization issues we've been seeing, but we may still just want to implement a proper virtualization library.
=> Link card virtualization tweak

apps/web/ui/workspaces/pro-banner.tsx
Also increases "Don't show again" expiration to 180 days
=> ENG-327: Move upgrade popup above help button

apps/web/lib/integrations/slack/slash-commands.ts
- Find the matching Dub user for a given Slack user
=> Updates the Slack integration

apps/web/lib/tinybird/record-click.ts, packages/utils/src/constants/countries.ts
Revert to our old setup (ref https://github.com/dubinc/dub/commit/841d3edf6a4c6d75ec11a34f8c80802b29b190c6)
[Reasoning](https://x.com/pontusab/status/1825157404142571739) – inspired by @pontusab ;)
=> Improve eu country filter logic

apps/web/ui/links/short-link-input-new.tsx, apps/web/ui/modals/link-builder/targeting-modal.tsx, packages/ui/src/combobox/index.tsx
https://github.com/user-attachments/assets/e134944f-ebeb-4ad4-8aed-667106efa5b9
=> Update combobox+input focus states

apps/web/app/api/qr/route.tsx, apps/web/lib/qr/api.tsx, apps/web/package.json, pnpm-lock.yaml
Currently blocked by: https://github.com/vercel/satori/issues/592
=> Add logo support to QR API

apps/web/app/not-found.tsx
In this Pr, i improved the not found page 
Fixes #1325
=> improved not found page

packages/utils/src/functions/capitalize.ts
=> chore: update capitalize.ts

apps/web/ui/modals/link-builder/constants.ts, apps/web/ui/modals/link-builder/targeting-modal.tsx, apps/web/ui/modals/link-builder/utm-modal.tsx
https://github.com/user-attachments/assets/b350489b-25af-4b41-8e27-6a279ae799dd
=> ENG-536: Connect UTM builder to targeting

apps/web/app/api/domains/default/route.ts, apps/web/app/api/domains/route.ts, apps/web/app/api/tags/count/route.ts, apps/web/app/api/tags/route.ts, apps/web/app/app.dub.co/(dashboard)/[slug]/page-client.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/settings/domains/page-client.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/settings/tags/page-client.tsx, apps/web/lib/swr/use-tags-count.ts, apps/web/lib/swr/use-tags.ts, apps/web/lib/zod/schemas/tags.ts, apps/web/ui/analytics/toggle.tsx, apps/web/ui/links/use-link-filters.tsx, apps/web/ui/modals/link-builder/tag-select.tsx, packages/ui/src/filter/filter-select.tsx, packages/ui/src/filter/types.ts
Adds pagination and filtering to tags endpoints and updates the link builder tag selector and tags settings page accordingly.
=> Add pagination and filtering to tags

apps/web/ui/analytics/share-button.tsx, apps/web/ui/analytics/toggle.tsx
Fix overflow in analytics toggle
=> Fix analytics toggle overflow

apps/web/app/partners.dub.co/(dashboard)/[partnerId]/[programId]/hero-background.tsx, apps/web/app/partners.dub.co/(dashboard)/[partnerId]/[programId]/page-client.tsx, apps/web/lib/analytics/get-events.ts, apps/web/lib/zod/schemas/leads.ts, apps/web/ui/analytics/events/events-table.tsx, apps/web/ui/analytics/events/use-column-visibility.ts
* Obfuscate lead events
* Add earnings to sales events table
* Fix overview overflow issues
=> Partners tweaks

apps/web/ui/analytics/bar-list.tsx
=> Fix analytics card truncation

apps/web/ui/webhooks/webhook-events.tsx, packages/ui/src/sheet.tsx
New sheet component pulled from the folders PR (#1258)
https://github.com/user-attachments/assets/b8936fed-e559-43b6-89e2-612c8aedc845
=> New `@dub/ui` Sheet component

apps/web/app/partners.dub.co/(dashboard)/[partnerId]/settings/payouts/page-client.tsx
=> Fix Dots drawer size for mobile

apps/web/app/app.dub.co/(dashboard)/[slug]/settings/payouts/page-client.tsx
=> Fix workspace settings payouts on mobile

package.json, packages/ui/package.json, packages/ui/src/combobox/index.tsx, pnpm-lock.yaml
Resolves issues related to my attempt at fixing combobox input focus within drawers ([commit](https://github.com/dubinc/dub/commit/7b2aa6c462d0326c841298d317cfc3bbaa6017b7?w=1))
It seems like we can get things working everywhere by ensuring all of our packages are using the same Radix UI versions. The downside is that we're probably more likely to run into compatibility problems and upgrading packages could be a little more complicated, but I don't see another solution to get all of the portal focus scopes to play nicely with each other.
=> Fix Combobox / nested portal focus scopes

packages/ui/package.json, packages/ui/src/footer.tsx
=> Update `@dub/ui` `Footer`

packages/ui/package.json, packages/ui/src/grid.tsx
Add unique ID to `@dub/ui` `Grid`
=> Fix different `@dub/ui` `Grid`s on the same page

apps/web/lib/swr/use-domain.ts, apps/web/ui/links/link-title-column.tsx, apps/web/ui/modals/link-builder/qr-code-preview.tsx, apps/web/ui/modals/link-qr-modal.tsx
=> Fix useDomain()

apps/web/app/api/user/password/route.ts, apps/web/lib/actions/request-password-reset.ts
This pull request includes updates to the password reset functionality to improve efficiency and prevent race conditions. The most important changes include updating the user password and deleting old password reset tokens in a single transaction, and ensuring sequential execution of password reset token operations.
Password reset functionality improvements:
* [`apps/web/app/api/user/password/route.ts`](diffhunk://#diff-7affb025a8b81f24c420e803fcda39c02ddfbc0778ed50fbaabed185d5d2c31cL46-R61): Updated the user password and deleted old password reset tokens using `Promise.all` to perform both operations concurrently.
* [`apps/web/lib/actions/request-password-reset.ts`](diffhunk://#diff-95045e3e7de3258568f02b5dbf60cb925a4deefbf01a425f750e2cf35665a731L44-R53): Modified the password reset …
=> Delete password reset tokens after a user updates their password.

packages/utils/src/constants/pricing.tsx
Will require a `@dub/utils` release
=> Update conversion/sales limits

apps/web/app/app.dub.co/(dashboard)/[slug]/settings/billing/plan-usage.tsx, apps/web/ui/layout/sidebar/usage.tsx
=> Add minimum usage bar of 1% for usage > 0

apps/web/app/api/integrations/uninstall/route.ts, apps/web/app/api/slack/callback/route.ts, apps/web/app/api/webhooks/route.ts, apps/web/lib/api/links/create-link.ts, apps/web/lib/api/links/update-link.ts, apps/web/lib/integrations/segment/install.ts, apps/web/lib/webhook/cache.ts, apps/web/lib/webhook/create-webhook.ts, apps/web/lib/webhook/update-webhook.ts
This pull request includes several updates and improvements across multiple files, focusing primarily on webhook management and integration handling. The most important changes include the addition of webhook caching, improvements in webhook creation and update processes, and modifications to the handling of Slack and Segment integrations.
* [`apps/web/lib/webhook/cache.ts`](diffhunk://#diff-6727bb1ce08a0365555c6f864d2f13f78b6d8532b760e3a83b071a5389416396R43-R56): Added a `deleteMany` method to the `WebhookCache` class to support bulk deletion of webhooks.
* [`apps/web/lib/webhook/update-webhook.ts`](diffhunk://#diff-5cc9eb23f3bd27c81faa572cac5a84a411a5c19514f2d0e517e6a3b6a22ccad2R26-R114): Introduced the `propagateWebhookTriggerChanges` function to update webhook triggers and cache them …
=> Webhooks updates

apps/web/ui/links/short-link-input.tsx, apps/web/ui/modals/link-builder/conversion-tracking-toggle.tsx, apps/web/ui/modals/link-builder/link-preview.tsx, apps/web/ui/modals/link-builder/og-modal.tsx, apps/web/ui/modals/link-builder/qr-code-preview.tsx, apps/web/ui/modals/link-builder/use-metatags.ts, apps/web/ui/modals/link-qr-modal.tsx
https://github.com/user-attachments/assets/80b1894d-a608-4708-b339-9d3602f9ada5
=> Improve Custom Link Preview

apps/web/app/api/patch-redirect/route.ts, apps/web/lib/middleware/link.ts, apps/web/lib/middleware/utils/has-empty-search-params.ts
Temp solution until this is fixed on Vercel's Edge Middleware
=> Patch fix for broken redirect

apps/web/app/api/links/[linkId]/route.ts, apps/web/app/api/partners/links/route.ts, apps/web/lib/api/links/process-link.ts
- optimize program checks
- allow deleting links with programId on API level
=> skipProgramChecks

apps/web/app/app.dub.co/(dashboard)/[slug]/settings/integrations/[integrationSlug]/page-client.tsx, apps/web/app/app.dub.co/(share)/share/[dashboardId]/page.tsx, apps/web/lib/analytics/get-analytics.ts, apps/web/lib/fetchers/get-dashboard.ts, apps/web/lib/zod/schemas/analytics-response.ts, apps/web/ui/analytics/link-preview.tsx, apps/web/ui/analytics/top-links.tsx, apps/web/ui/links/comments-badge.tsx, apps/web/ui/links/link-title-column.tsx, apps/web/ui/shared/markdown.tsx
=> Add link comments to Analytics tab

apps/web/app/partners.dub.co/(dashboard)/settings/payouts/payout-stats-and-settings.tsx
Updated the connected bank account number to neutral from gray.
=> Connected account color change

apps/web/app/app.dub.co/(dashboard)/[slug]/settings/integrations/featured-integrations.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/settings/integrations/integrations-cards.tsx, packages/ui/src/icons/card-discover.tsx, packages/ui/src/icons/dub-crafted-shield.tsx
* Fixes JSX SVG attributes in `DubCraftedShield` and `CardDiscover` icons
* Scopes `CardDiscover` `id`s w/ `useId` to prevent collisions
* Adds missing`key`s to`FeaturedIntegrationsLoader `
* Removes `async` from `IntegrationsCards` (client component)
=> Quick misc. fixes

apps/web/app/app.dub.co/embed/inline/hero-background.tsx, apps/web/app/app.dub.co/embed/inline/loading.tsx, apps/web/app/app.dub.co/embed/inline/page-client.tsx, apps/web/app/partners.dub.co/(dashboard)/programs/[programSlug]/page-client.tsx, packages/ui/src/icons/nucleo/index.ts, packages/ui/src/icons/nucleo/money-bill.tsx
=> Update embed UI

apps/web/app/api/links/bulk/route.ts, apps/web/lib/api/links/utils/check-if-links-have-folders.ts, apps/web/lib/folder/permissions.ts, apps/web/tests/links/create-link-error.test.ts
- Add folder checks to following APIs
- `POST /api/links/bulk`
- `PATCH /api/links/bulk`
- `DELETE /api/links/bulk`
- Updated the `create-link-error` test with a few more cases
=> Folder contd.

packages/ui/src/input-select.tsx
Reduces duplication and includes icon in a flex row instead of absolute positioning
=> Fix `InputSelect` icons

apps/web/lib/analytics/get-events.ts, apps/web/lib/api/customers/get-customer-or-throw.ts, apps/web/lib/rewardful/import-referrals.ts, apps/web/lib/tinybird/record-lead.ts, apps/web/lib/webhook/sample-events/lead-created.json, apps/web/lib/webhook/sample-events/sale-created.json, apps/web/lib/zod/schemas/leads.ts, apps/web/tests/utils/helpers.ts
for [higher rate limits](https://www.dicebear.com/how-to-use/http-api/#rate-limits)
also made a small update to recordLeadWithTimestamp for import-referrals
=> update dicebear to use svg

apps/web/ui/partners/create-payout-sheet.tsx
Added "the" to the placeholder text.
=> Grammar update

apps/web/app/api/track/sale/route.ts
Related: 
- https://github.com/nextauthjs/next-auth/issues/10773
- https://github.com/prisma/prisma/issues/20566#issuecomment-2021594203
- https://zenstack.dev/blog/adapt-to-edge#a-bonus-trap
=> Start moving from edge to node

apps/web/app/api/track/lead/route.ts, apps/web/tests/tracks/track-lead.test.ts
Only store first event if it's an array
=> Account for leadEventPayload array

apps/web/app/app.dub.co/(dashboard)/[slug]/settings/library/folders/page-client.tsx, apps/web/lib/swr/use-links-count.ts, apps/web/ui/folders/folder-card.tsx, apps/web/ui/links/archived-links-hint.tsx, apps/web/ui/links/links-container.tsx, apps/web/ui/links/use-link-filters.tsx, packages/ui/src/hooks/use-intersection-observer.ts
Fetch link counts in a separate request, only when the folder card is visible
=> Optimize folder link counts

apps/web/app/app.dub.co/(dashboard)/[slug]/programs/[programId]/payouts/payout-table.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/programs/[programId]/payouts/use-payout-filters.tsx, apps/web/app/app.dub.co/(dashboard)/[slug]/programs/[programId]/sales/use-sale-filters.tsx, packages/ui/src/hooks/use-router-stuff.ts
Prevents re-rendering the entire tables when the filter search changes
=> Improve performance of sales and payouts tables

packages/ui/package.json, packages/ui/src/nav/nav-mobile.tsx
=> Add auth/dashboard buttons to main mobile nav

apps/web/app/app.dub.co/embed/referrals/activity.tsx
=> Add referral embed activity empty state

packages/email/src/templates/api-key-created.tsx, packages/email/src/templates/clicks-exceeded.tsx, packages/email/src/templates/clicks-summary.tsx, packages/email/src/templates/confirm-email-change.tsx, packages/email/src/templates/domain-claimed.tsx, packages/email/src/templates/domain-deleted.tsx, packages/email/src/templates/failed-payment.tsx, packages/email/src/templates/folder-edit-access-requested.tsx, packages/email/src/templates/integration-installed.tsx, packages/email/src/templates/invalid-domain.tsx, packages/email/src/templates/links-imported.tsx, packages/email/src/templates/links-limit.tsx, packages/email/src/templates/login-link.tsx, packages/email/src/templates/new-referral-signup.tsx, packages/email/src/templates/new-sale-alert-partner.tsx, packages/email/src/templates/new-sale-alert-program-owner.tsx, packages/email/src/templates/partner-application-approved.tsx, packages/email/src/templates/partner-application-received.tsx, packages/email/src/templates/partner-invite.tsx, packages/email/src/templates/partner-payout-confirmed.tsx, packages/email/src/templates/partner-payout-sent.tsx, packages/email/src/templates/referral-invite.tsx, packages/email/src/templates/reset-password-link.tsx, packages/email/src/templates/verify-email.tsx, packages/email/src/templates/webhook-added.tsx, packages/email/src/templates/webhook-disabled.tsx, packages/email/src/templates/webhook-failed.tsx, packages/email/src/templates/workspace-invite.tsx
- Updates to language where we could improve
- Updated styling to the buttons to make the marketing site and app
- Update to the `new-sale-alert-program-owner` to make it more clear who's getting the sale, and where it came from.
=> Email updates

apps/web/app/api/cron/program-application-reminder/route.ts, apps/web/app/partners.dub.co/(apply)/[programSlug]/apply/form.tsx, apps/web/app/partners.dub.co/(apply)/[programSlug]/apply/success/page.tsx, apps/web/app/partners.dub.co/(apply)/[programSlug]/layout.tsx, apps/web/app/partners.dub.co/(auth)/(default)/register/page.tsx, apps/web/lib/actions/partners/create-program-application.ts, apps/web/scripts/tella/remind-applications.ts, packages/email/src/templates/program-application-reminder.tsx, packages/prisma/schema/partner.prisma, packages/prisma/schema/program.prisma
=> Application Success Improvements

apps/web/app/api/partners/links/route.ts, apps/web/lib/openapi/partners/index.ts, apps/web/lib/openapi/partners/retrieve-partner-links.ts, apps/web/lib/zod/schemas/partners.ts
```
[
{
id: 'link_1JQDZZCW3VF4DHMR3F7KF81CD',
domain: 'dub.sh',
key: 'kiran',
shortLink: 'https://dub.sh/kiran',
url: 'https://google.com',
clicks: 4,
leads: 22,
sales: 0,
saleAmount: 0
}
]
```
=> Add `dub.partners.retrieveLinks`

apps/web/app/app.dub.co/(dashboard)/[slug]/links/[...link]/page-client.tsx, apps/web/ui/folders/folder-dropdown.tsx, apps/web/ui/links/link-builder/controls/link-builder-folder-selector.tsx, apps/web/ui/links/link-builder/link-action-bar.tsx, apps/web/ui/links/link-builder/link-builder-header.tsx, apps/web/ui/links/link-builder/more-dropdown.tsx, apps/web/ui/links/link-controls.tsx, apps/web/ui/modals/link-builder/index.tsx
* Moves folder dropdowns
* Adds duplicating from the link builder page
=> Link builder updates

apps/web/app/partners.dub.co/(dashboard)/settings/payouts/use-payout-filters.tsx, apps/web/ui/layout/sidebar/partner-program-dropdown.tsx
* Fixes program dropdown Settings font size + truncation outside scroll area
* Fixes clearing filters on `partners.dub.co/settings/payouts`
=> Quick fixes

packages/ui/src/date-picker/date-range-picker.tsx
=> Add scroll fade to date range presets

apps/web/ui/modals/delete-workspace-modal.tsx
Required slug input to prevent workspace deletion without proper validation. Also cleaned up unnecessary dependencies in useCallback hook.
Good to be back! Finally got a new machine that can actually handle this beast of a codebase. Before I was trying to fix issues without even being able to run it locally, which was a real struggle 🤓
=> Fixed the bug where you could delete a workspace without entering the slug

apps/web/lib/analytics/get-analytics.ts, apps/web/lib/zod/schemas/analytics-response.ts, apps/web/ui/analytics/locations.tsx, packages/tinybird/pipes/v2_cities.pipe
Lowkey kinda mindblowing how many "Springfield" cities there are in the US... 🤯
=> Include region data in cities groupBy

apps/web/next.config.js, apps/web/package.json, pnpm-lock.yaml
As per https://github.com/boxyhq/jackson/issues/3745#issuecomment-2754731322 👀
=> Upgrade boxyhq package

apps/web/app/api/domains/[domain]/transfer/route.ts, apps/web/app/api/folders/route.ts, apps/web/app/api/links/[linkId]/route.ts, apps/web/app/api/links/route.ts, apps/web/app/api/links/upsert/route.ts, apps/web/app/api/workspaces/[idOrSlug]/billing/upgrade/route.ts, apps/web/lib/zod/schemas/links.ts, apps/web/lib/zod/schemas/misc.ts
- Fix "Open Redirect on Stripe Checkout Integration via baseUrl"
- Fix folder limit bypass
- Improve the image validation for the links endpoint
=> Improve folder usage limit check and image validation

apps/web/app/app.dub.co/(dashboard)/[slug]/programs/[programId]/partners/partner-table.tsx
If the partner is not already loaded and found in the partners array, fetch it separately to display in the sheet.
Because the partner's status affects which sheet to display, it was easiest to add this logic in `PartnerTable`
=> Partner sheet fetching improvement

apps/web/lib/api/links/get-links-for-workspace.ts, packages/prisma/schema/link.prisma
+ also rearrange search criteria
=> Add index on tenantId on Link table

apps/web/ui/domains/add-edit-domain-form.tsx
Changed the color to be more informative, and less ALERT!
Made the language more clear in the current situation, and what happens if you connect to Dub.
=> Connect domain messaging

apps/web/lib/zod/schemas/program-lander.ts, apps/web/ui/partners/design/modals/accordion-block-modal.tsx, apps/web/ui/partners/design/modals/earnings-calculator-block-modal.tsx, apps/web/ui/partners/design/modals/files-block-modal.tsx, apps/web/ui/partners/lander-blocks/AccordionBlock.tsx, apps/web/ui/partners/lander-blocks/BlockDescription.tsx, apps/web/ui/partners/lander-blocks/FilesBlock.tsx, apps/web/ui/partners/lander-blocks/TextBlock.tsx, apps/web/ui/partners/lander-blocks/earnings-calculator-block.tsx
* Default title + description for Earnings Calculator
* Block spacing fixes
* Scroll container fixes
=> Earnings Calculator Defaults + Misc. Improvements

apps/web/app/app.dub.co/(dashboard)/[slug]/(ee)/program/partners/[partnerId]/comments/page-client.tsx
Handle newlines & links properly
=> Improve comment formatting
